version: '3.9'

services:
  influxdb-k6:
    image: influxdb:2.7
    container_name: influxdb2
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=123456789
      - DOCKER_INFLUXDB_INIT_ORG=T-EVOLVERS
      - DOCKER_INFLUXDB_INIT_BUCKET=k6
      - DOCKER_INFLUXDB_INIT_RETENTION=30d
    networks:
      - grafana

  visualizer-metrics:
    image: grafana/grafana:9.1.6
    container_name: metrics-analytics
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/
    networks:
      - grafana
    depends_on:
      - influxdb-k6

networks:
  grafana:
    driver: bridge