version: 2.1

executors:
  base:
    docker:
      - image: maven:3.9-eclipse-temurin-17-alpine
    working_directory: ~/app

jobs:
  run-jmeterdsl:
    executor: base
    steps:
      - checkout
      - run:
          name: Set up Maven Cache
          command: |
            mkdir -p ~/.m2
            echo "<settings><localRepository>/home/circleci/.m2/repository</localRepository></settings>" > ~/.m2/settings.xml
      - restore_cache:
          keys:
            - maven-cache-{{ checksum "pom.xml" }}
            - maven-cache-
      - run:
          name: Install Dependencies
          command: mvn dependency:resolve
      - save_cache:
          paths:
            - ~/.m2/repository
          key: maven-cache-{{ checksum "pom.xml" }}
      - run:
          name: Compile and Run Tests
          command: mvn clean test
      - persist_to_workspace:
          root: .
          paths:
            - target
      - store-results:
          path: target/**
          destination: results

workflows:
  version: 2
  build-and-publish:
    jobs:
      - run-jmeterdsl
      - publish-results:
          requires:
            - run-jmeterdsl